/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StationenkartenRouteImport } from './routes/stationenkarten'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ArbeitsauftragRouteImport } from './routes/arbeitsauftrag'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KlasseClassIdRouteImport } from './routes/klasse.$classId'
import { Route as KlasseClassIdQuickRouteImport } from './routes/klasse.$classId.quick'
import { Route as KlasseClassIdDisziplinenRouteImport } from './routes/klasse.$classId.disziplinen'

const StationenkartenRoute = StationenkartenRouteImport.update({
  id: '/stationenkarten',
  path: '/stationenkarten',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbeitsauftragRoute = ArbeitsauftragRouteImport.update({
  id: '/arbeitsauftrag',
  path: '/arbeitsauftrag',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KlasseClassIdRoute = KlasseClassIdRouteImport.update({
  id: '/klasse/$classId',
  path: '/klasse/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const KlasseClassIdQuickRoute = KlasseClassIdQuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => KlasseClassIdRoute,
} as any)
const KlasseClassIdDisziplinenRoute =
  KlasseClassIdDisziplinenRouteImport.update({
    id: '/disziplinen',
    path: '/disziplinen',
    getParentRoute: () => KlasseClassIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arbeitsauftrag': typeof ArbeitsauftragRoute
  '/datenschutz': typeof DatenschutzRoute
  '/einstellungen': typeof EinstellungenRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/stationenkarten': typeof StationenkartenRoute
  '/klasse/$classId': typeof KlasseClassIdRouteWithChildren
  '/klasse/$classId/disziplinen': typeof KlasseClassIdDisziplinenRoute
  '/klasse/$classId/quick': typeof KlasseClassIdQuickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arbeitsauftrag': typeof ArbeitsauftragRoute
  '/datenschutz': typeof DatenschutzRoute
  '/einstellungen': typeof EinstellungenRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/stationenkarten': typeof StationenkartenRoute
  '/klasse/$classId': typeof KlasseClassIdRouteWithChildren
  '/klasse/$classId/disziplinen': typeof KlasseClassIdDisziplinenRoute
  '/klasse/$classId/quick': typeof KlasseClassIdQuickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arbeitsauftrag': typeof ArbeitsauftragRoute
  '/datenschutz': typeof DatenschutzRoute
  '/einstellungen': typeof EinstellungenRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/stationenkarten': typeof StationenkartenRoute
  '/klasse/$classId': typeof KlasseClassIdRouteWithChildren
  '/klasse/$classId/disziplinen': typeof KlasseClassIdDisziplinenRoute
  '/klasse/$classId/quick': typeof KlasseClassIdQuickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arbeitsauftrag'
    | '/datenschutz'
    | '/einstellungen'
    | '/impressum'
    | '/login'
    | '/stationenkarten'
    | '/klasse/$classId'
    | '/klasse/$classId/disziplinen'
    | '/klasse/$classId/quick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arbeitsauftrag'
    | '/datenschutz'
    | '/einstellungen'
    | '/impressum'
    | '/login'
    | '/stationenkarten'
    | '/klasse/$classId'
    | '/klasse/$classId/disziplinen'
    | '/klasse/$classId/quick'
  id:
    | '__root__'
    | '/'
    | '/arbeitsauftrag'
    | '/datenschutz'
    | '/einstellungen'
    | '/impressum'
    | '/login'
    | '/stationenkarten'
    | '/klasse/$classId'
    | '/klasse/$classId/disziplinen'
    | '/klasse/$classId/quick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArbeitsauftragRoute: typeof ArbeitsauftragRoute
  DatenschutzRoute: typeof DatenschutzRoute
  EinstellungenRoute: typeof EinstellungenRoute
  ImpressumRoute: typeof ImpressumRoute
  LoginRoute: typeof LoginRoute
  StationenkartenRoute: typeof StationenkartenRoute
  KlasseClassIdRoute: typeof KlasseClassIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stationenkarten': {
      id: '/stationenkarten'
      path: '/stationenkarten'
      fullPath: '/stationenkarten'
      preLoaderRoute: typeof StationenkartenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbeitsauftrag': {
      id: '/arbeitsauftrag'
      path: '/arbeitsauftrag'
      fullPath: '/arbeitsauftrag'
      preLoaderRoute: typeof ArbeitsauftragRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klasse/$classId': {
      id: '/klasse/$classId'
      path: '/klasse/$classId'
      fullPath: '/klasse/$classId'
      preLoaderRoute: typeof KlasseClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klasse/$classId/quick': {
      id: '/klasse/$classId/quick'
      path: '/quick'
      fullPath: '/klasse/$classId/quick'
      preLoaderRoute: typeof KlasseClassIdQuickRouteImport
      parentRoute: typeof KlasseClassIdRoute
    }
    '/klasse/$classId/disziplinen': {
      id: '/klasse/$classId/disziplinen'
      path: '/disziplinen'
      fullPath: '/klasse/$classId/disziplinen'
      preLoaderRoute: typeof KlasseClassIdDisziplinenRouteImport
      parentRoute: typeof KlasseClassIdRoute
    }
  }
}

interface KlasseClassIdRouteChildren {
  KlasseClassIdDisziplinenRoute: typeof KlasseClassIdDisziplinenRoute
  KlasseClassIdQuickRoute: typeof KlasseClassIdQuickRoute
}

const KlasseClassIdRouteChildren: KlasseClassIdRouteChildren = {
  KlasseClassIdDisziplinenRoute: KlasseClassIdDisziplinenRoute,
  KlasseClassIdQuickRoute: KlasseClassIdQuickRoute,
}

const KlasseClassIdRouteWithChildren = KlasseClassIdRoute._addFileChildren(
  KlasseClassIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArbeitsauftragRoute: ArbeitsauftragRoute,
  DatenschutzRoute: DatenschutzRoute,
  EinstellungenRoute: EinstellungenRoute,
  ImpressumRoute: ImpressumRoute,
  LoginRoute: LoginRoute,
  StationenkartenRoute: StationenkartenRoute,
  KlasseClassIdRoute: KlasseClassIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
