/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StationenkartenRouteImport } from './routes/stationenkarten'
import { Route as PostenkartenRouteImport } from './routes/postenkarten'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as ArbeitsauftragRouteImport } from './routes/arbeitsauftrag'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KlasseClassIdRouteImport } from './routes/klasse.$classId'
import { Route as KlasseClassIdQuickRouteImport } from './routes/klasse.$classId.quick'

const StationenkartenRoute = StationenkartenRouteImport.update({
  id: '/stationenkarten',
  path: '/stationenkarten',
  getParentRoute: () => rootRouteImport,
} as any)
const PostenkartenRoute = PostenkartenRouteImport.update({
  id: '/postenkarten',
  path: '/postenkarten',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbeitsauftragRoute = ArbeitsauftragRouteImport.update({
  id: '/arbeitsauftrag',
  path: '/arbeitsauftrag',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KlasseClassIdRoute = KlasseClassIdRouteImport.update({
  id: '/klasse/$classId',
  path: '/klasse/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const KlasseClassIdQuickRoute = KlasseClassIdQuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => KlasseClassIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arbeitsauftrag': typeof ArbeitsauftragRoute
  '/einstellungen': typeof EinstellungenRoute
  '/login': typeof LoginRoute
  '/postenkarten': typeof PostenkartenRoute
  '/stationenkarten': typeof StationenkartenRoute
  '/klasse/$classId': typeof KlasseClassIdRouteWithChildren
  '/klasse/$classId/quick': typeof KlasseClassIdQuickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arbeitsauftrag': typeof ArbeitsauftragRoute
  '/einstellungen': typeof EinstellungenRoute
  '/login': typeof LoginRoute
  '/postenkarten': typeof PostenkartenRoute
  '/stationenkarten': typeof StationenkartenRoute
  '/klasse/$classId': typeof KlasseClassIdRouteWithChildren
  '/klasse/$classId/quick': typeof KlasseClassIdQuickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arbeitsauftrag': typeof ArbeitsauftragRoute
  '/einstellungen': typeof EinstellungenRoute
  '/login': typeof LoginRoute
  '/postenkarten': typeof PostenkartenRoute
  '/stationenkarten': typeof StationenkartenRoute
  '/klasse/$classId': typeof KlasseClassIdRouteWithChildren
  '/klasse/$classId/quick': typeof KlasseClassIdQuickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arbeitsauftrag'
    | '/einstellungen'
    | '/login'
    | '/postenkarten'
    | '/stationenkarten'
    | '/klasse/$classId'
    | '/klasse/$classId/quick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arbeitsauftrag'
    | '/einstellungen'
    | '/login'
    | '/postenkarten'
    | '/stationenkarten'
    | '/klasse/$classId'
    | '/klasse/$classId/quick'
  id:
    | '__root__'
    | '/'
    | '/arbeitsauftrag'
    | '/einstellungen'
    | '/login'
    | '/postenkarten'
    | '/stationenkarten'
    | '/klasse/$classId'
    | '/klasse/$classId/quick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArbeitsauftragRoute: typeof ArbeitsauftragRoute
  EinstellungenRoute: typeof EinstellungenRoute
  LoginRoute: typeof LoginRoute
  PostenkartenRoute: typeof PostenkartenRoute
  StationenkartenRoute: typeof StationenkartenRoute
  KlasseClassIdRoute: typeof KlasseClassIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stationenkarten': {
      id: '/stationenkarten'
      path: '/stationenkarten'
      fullPath: '/stationenkarten'
      preLoaderRoute: typeof StationenkartenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postenkarten': {
      id: '/postenkarten'
      path: '/postenkarten'
      fullPath: '/postenkarten'
      preLoaderRoute: typeof PostenkartenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbeitsauftrag': {
      id: '/arbeitsauftrag'
      path: '/arbeitsauftrag'
      fullPath: '/arbeitsauftrag'
      preLoaderRoute: typeof ArbeitsauftragRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klasse/$classId': {
      id: '/klasse/$classId'
      path: '/klasse/$classId'
      fullPath: '/klasse/$classId'
      preLoaderRoute: typeof KlasseClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klasse/$classId/quick': {
      id: '/klasse/$classId/quick'
      path: '/quick'
      fullPath: '/klasse/$classId/quick'
      preLoaderRoute: typeof KlasseClassIdQuickRouteImport
      parentRoute: typeof KlasseClassIdRoute
    }
  }
}

interface KlasseClassIdRouteChildren {
  KlasseClassIdQuickRoute: typeof KlasseClassIdQuickRoute
}

const KlasseClassIdRouteChildren: KlasseClassIdRouteChildren = {
  KlasseClassIdQuickRoute: KlasseClassIdQuickRoute,
}

const KlasseClassIdRouteWithChildren = KlasseClassIdRoute._addFileChildren(
  KlasseClassIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArbeitsauftragRoute: ArbeitsauftragRoute,
  EinstellungenRoute: EinstellungenRoute,
  LoginRoute: LoginRoute,
  PostenkartenRoute: PostenkartenRoute,
  StationenkartenRoute: StationenkartenRoute,
  KlasseClassIdRoute: KlasseClassIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
